### ISSUE TITLE
Cannot post cars

### ISSUE THREAD

**Issue by qwerty15202** [jackm/kijiji-manager#13]
Everytime I try to upload a car I get the following error
{'carmodel': ['Not a valid choice']}

**Comment by jackm** [comment]
I believe this was fixed already in 33d0a7f. See issue #12 
Did you pull the latest commit?

**Comment by qwerty15202** [comment]
sorry new to this. How do I pull the latest commit.
Thanks in advance.

**Comment by jackm** [comment]
[git pull tutorial](https://www.atlassian.com/git/tutorials/syncing/git-pull).
You can also download from the [published releases](../releases).

**Comment by qwerty15202** [comment]
solved! Thank you so much!
