### ISSUE TITLE
Ebay API Unknown Error

### ISSUE THREAD

**Issue by EdwardOak** [jackm/kijiji-manager#15]
I keep getting this when trying to post new products with full HD pictures, no phone number because it makes the thing bug. 

Does this still work?

How do you guys post.

**Comment by EdwardOak** [comment]
I'm trying to re-install since I may not have been using the latest version. 

Upon re-installing I'm getting the following error when running `python -m kijiji_manager`

`  File "kijiji_manager/app.py", line 32
    f"Either specify one with the `-c` flag, or put one named '{config_name}' in the Flask instance folder at the path below.\n"
    ^
SyntaxError: invalid syntax`

**Comment by EdwardOak** [comment]
sourced venv properly

**Comment by EdwardOak** [comment]
instance folder was in /kijiji_manager/instance
instead of /kijiji-manager/instance

After moving folder back, the same error gets shown with python and the error for python3 (i tested) shows this error:
`  File "/home/gary_oak_rk/Desktop/KIJIJI/kijiji-manager/kijiji_manager/forms/post.py", line 3, in <module>
    import phonenumbers
ModuleNotFoundError: No module named 'phonenumbers'`

**Comment by EdwardOak** [comment]
So I tried to: 
`pip install phonenumbers
Collecting phonenumbers
  Using cached https://files.pythonhosted.org/packages/e9/b3/8d653bab66c2900bcb2151062e496ffb681b6794ef8e6cc5df9b5e92a824/phonenumbers-8.12.27-py2.py3-none-any.whl
Installing collected packages: phonenumbers
Successfully installed phonenumbers-8.12.27`

**Comment by EdwardOak** [comment]
and it changed nothing. 
python gives the same syntax error and python3 tells me phonenumbers module is not installed, albeit installed seconds ago.

Is this Kijiji-Manager thing still working or abandonned?

**Comment by jackm** [comment]
> I'm trying to re-install since I may not have been using the latest version.
> 
> Upon re-installing I'm getting the following error when running `python -m kijiji_manager`
> 
> ` File "kijiji_manager/app.py", line 32 f"Either specify one with the`-c` flag, or put one named '{config_name}' in the Flask instance folder at the path below.\n" ^ SyntaxError: invalid syntax`

It is giving a SyntaxError because the versionof Python you are using does not understand f-strings. This is because you are not using Python version 3.6 or higher. Python 3.6+ is a requirement for running this project. Make sure you are using Python >=3.6 and not Python 2.

For the issues with missing Python packages, I suggest you follow the installation steps again. Somewhere you are either not using the right virtualenv, not activating the virtualenv or you are using the wrong Python binary which does not know about the dependency packages.

**Comment by EdwardOak** [comment]
My python version is latest AND the outdated *Kijiji-manager* version works (but cannot post) 
I also specified I tried using python3 & python
This issue happen during a secondary install/deploy.

**Comment by EdwardOak** [comment]
Must have been my issue. Working now.
