### ISSUE TITLE
Default location and postcode

### ISSUE THREAD

**Issue by kobemtl** [jackm/kijiji-manager#19]
Hi, first I want to say thank you for the great project. It really helps. Just don't understand why kijiji not providing simple repost feature. 

For the CFG file is it possible to have some default value such default location and postcode set? So we don't need to choose that from the dropdown list every time. 

Again appreciate your good work. Keep going.

**Comment by jackm** [comment]
Preliminary work for this feature is on the [feature/default-form-values](../tree/feature/default-form-values) branch.

**Comment by jackm** [comment]
Merged into master and released as v0.1.7 (4ba3243)
