### ISSUE TITLE
Can't post house rental ads

### ISSUE THREAD

**Issue by aceycodo** [jackm/kijiji-manager#2]
When ever I try to post a house rental ad I get a 500 Internal Server Error

**Comment by jackm** [comment]
Which specific Kijiji category are you attempting to post an ad to?

**Comment by rybodiddly** [comment]
if I recall, it was a date formatting issue. was fixed in mine a while ago (check around line 638 in server.py).

**Comment by jackm** [comment]
Fixed in commit 7bdb6f0
