### ISSUE TITLE
Multiple Ads not being reposted

### ISSUE THREAD

**Issue by rockerguy1978** [jackm/kijiji-manager#21]
Hi,

When using the `repost all ads` button, not all the ads are reposted. I am running this project as a service on Ubuntu. Reviewing the service logs isn't showing any issue either.

**Comment by rockerguy1978** [comment]
I changed the delay timeout ([link](https://github.com/jackm/kijiji-manager/blob/43747e27ef821908db0f363f140df27aceb14bd8/kijiji_manager/views/ad.py#L416)]. Hopefully that is the cause of the issue.

**Comment by jackm** [comment]
Kijiji may have changed their duplicate ad detection algorithm where 3 minutes isn't a long enough time to avoid triggering it.
I'll have to play around with it and see what an appropriate wait time should be. Hopefully it doesn't need to be as long as 10 minutes.

**Comment by dudududodododedede** [comment]
I'm not experiencing any issues with the 3 minute delay. Did you get an email from kijiji saying they detected your ad as duplicate and they deleted it?

**Comment by rockerguy1978** [comment]
> I'm not experiencing any issues with the 3 minute delay. Did you get an email from kijiji saying they detected your ad as duplicate and they deleted it?

No. I did not receive an email.

**Comment by dudududodododedede** [comment]
Can you reliably reproduce the issue?

Have you tried running with debug mode on?

**Comment by rockerguy1978** [comment]
> Can you reliably reproduce the issue?

I have a script that logs into more than one accounts and makes a request to the repost all option. You can see the code [here](https://github.com/jackm/kijiji-manager/issues/6#issuecomment-925359270). I'll check again when the ads repost again. Every couple of days. That said, it appears to be happening to both accounts over the last week (first time I have noticed ads not being reposted).

> Have you tried running with debug mode on?

I just switched my service to run with the debug flag as on. Everything should write to the journalctl logs. I'll review once I notice ads missing again.

**Comment by rockerguy1978** [comment]
So script ran again this evening. 6/8 ads were reposted.

I reviewed the journalctl logs for the output as I re-ran the service with the debug argument and nothing notable was shown.

**Comment by rockerguy1978** [comment]
So I just checked again, I received the emails saying my ad was successfully reposted despite not being there. I then posted the AD again through the GUI manually. After that I received the emails from Kijiji again saying the ad was successfully posted, but the ads are not shown. I think my account is flagged or something.

Perhaps the frequency of my re-posting is too high - 3x a week.

**Comment by jackm** [comment]
I've heard from other people before that Kijiji will put rate limiting on certain accounts that they flag as being potentially abusive to the site.

It's possible that Kijiji is extending the minimum time period for their duplicate ad detection algorithm for accounts that have a high volume of ad postings. To me this makes sense as a way to mitigate spam.

Unfortunately this is a hard thing to test and get a conclusive answer on since the only good method is to just try posting ads and see if they succeed or not since we'll never have access to the Kijiji backend.

**Comment by rockerguy1978** [comment]
Thanks everyone,

Seems like the issue has gone away. Definitely not an issue with this project. I'm going to close this off.
