### ISSUE TITLE
Function Request: Char Count on Ad Title

### ISSUE THREAD

**Issue by thanksforkijijimanager** [jackm/kijiji-manager#25]
I think it would be great if the Ad Title entry on New Ad Posting had some sort of character counter feature or limiting the field to only accept 64 characters (I think that's the limit). This would prevent having to re-do the entire ad because too many characters will cause error. Currently copying and pasting ad titles to char counter on Google to make sure it's good before submitting ad. 

Thanks again =]

**Comment by jackm** [comment]
If you attempt to post an ad where one of the fields contains invalid data, it will show a message at the top of the page explaining which field(s) are incorrect. This should not clear any of the form contents so you won't have to re-enter any data - just correct the fields which are invalid.

For example if the ad title is too long the message will say `{'adtitle': ['Title must be between 8 and 64 characters']}`.

**Comment by thanksforkijijimanager** [comment]
Yes that is working, I see it now
Thanks
