### ISSUE TITLE
Ability to Modify Region/Location in xml file

### ISSUE THREAD

**Issue by adm-gis** [jackm/kijiji-manager#27]
Thanks to all the contributors, this app makes selling so much easier.

I spend some time between a couple of cities and it would be great to be able to update the region/postal code in the xml files and repost.  I've tried changing the postal code, but it still gets posted in the original city's region.  Maybe I am doing something wrong?

Thanks again

**Comment by prgrm** [comment]
You need to edit the location id as well. For example, in this url:

https://www.kijiji.ca/b-refrigerator-fridge/brantford/c696l1700206

The category id is 696 (refrigerators) and the location id is 1700206 (Brantford)
Edit these in the xml file:
<loc:location id="XXX"/>
<types:zip-code>XXXXXX</types:zip-code>

**Comment by adm-gis** [comment]
Excellent.  Thanks for clarifying.
