### ISSUE TITLE
KijijiApiException: Error acquiring geo location data

### ISSUE THREAD

**Issue by sajjadpirani** [jackm/kijiji-manager#32]
Shows this error when trying to post ad

**Comment by jackm** [comment]
This usually indicates a problem with the postal code provided. Are you certain that the postal code you entered is a real postal code?

**Comment by jijiow** [comment]
Currently have the same issue. Tried multiple postal codes from many different regions

**Comment by sajjadpirani** [comment]
Still happening to me, postal code is correct.

**Comment by jackm** [comment]
Have you updated to the latest version, and does the error say anything else besides "_Error acquiring geo location data_" ?

Would you be able to tell me the first three characters of the postal code you're trying to use?

**Comment by sajjadpirani** [comment]
> Have you updated to the latest version, and does the error say anything else besides "_Error acquiring geo location data_" ?
> 
> Would you be able to tell me the first three characters of the postal code you're trying to use?

Did a fresh setup with newest version, this is the exact error

Error acquiring geo location data: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

First 3 characters of postal code are M2J

**Comment by jackm** [comment]
Are you using MacOS? It seems that you may have to install Python certificates as described here: https://stackoverflow.com/a/53310545

This project uses the `pgeocode` package which needs to download a list of all Canadian postal code areas (first three digits) so it knows the geographic area of the postal code. For you it is failing at this step where it tries to download the postal codes file.

**Comment by jackm** [comment]
Problem is likely due to a Python installation problem on users system where SSL certificates were not installed. Using the official Python installers should take care of this step automatically.

Closing
