### ISSUE TITLE
manually posting an xml ad not working

### ISSUE THREAD

**Issue by HOLY-FROMAGE** [jackm/kijiji-manager#43]
The issue happens when I post an xml payload ad. I receive an email by kijiji saying the ad is active but the ad disapears seconds after. no trace on web kijiji / mobile app.
I don't get an email saying my ad was removed either. 

anybody else experiencing this issue?

ps; the same thing occurs when reposting an ad

**Comment by jackm** [comment]
What category is the ad in? Do you also have another existing ad with the same title and/or description?

It sounds to me like Kijiji is automatically removing the ad.

**Comment by HOLY-FROMAGE** [comment]
in nintendo switch category. I'll make more test today and post updates

**Comment by thanksforkijijimanager** [comment]
Things are working okay for me. Noticed this happening with one of my ads, same situation. All I did was change the title and it stopped getting deleted by Kijiji

**Comment by jackm** [comment]
Closing this as it is likely that the user tried to post an ad where the title and/or description body matched too closely with another one of their existing ads. Kijiji detects these as duplicate ads and automatically removes them.
