### ISSUE TITLE
Issue Posting New Ad. Photos Not accepted

### ISSUE THREAD

**Issue by rockerguy1978** [jackm/kijiji-manager#45]
I'm trying to post a new AD with 2 photos. I've ensured the photos are within the limits specified [here](https://help.kijiji.ca/helpdesk/basics/image-errors)

```
-rwxrwxrwx 1 topsecretuser topsecretuser 318K Jul 17 08:15 1.jpeg
-rwxrwxrwx 1 topsecretuser topsecretuser 256K Jul 17 08:15 2.jpeg
```

* Photos are JPEG. I also tried posting them as a PNG
* Both image dimensions are: 3072x1382. I also tried posting at 50% of this

I keep receiving the error `One of your images is not on an accepted service. Please upload your images again.`  I am also using the latest branch of this project. I understand there was someone who experienced a similar issue last week and it was patched in `v0.1.11`

**Comment by dudududodododedede** [comment]
after checking out the latest revision, are you sure you ran "pip install ." again? are you running in a venv?

**Comment by kobemtl** [comment]
I have the same issue by using the v0.1.11. Built and ran using the Dockerfile. 

I was using the temporary branch [new-image-upload-api branch](https://github.com/jackm/kijiji-manager/tree/new-image-upload-api) and everything works fine. with the latest release I get this error.

**Comment by kobemtl** [comment]
Just use the master branch re-built the docker image and works fine now.

**Comment by rockerguy1978** [comment]
Apologies for this, oddly enough I was on the master branch but hadn't pulled the latest updates (thought I had). It is working now after rebuilding the container on the newest commit.
