### ISSUE TITLE
Inability to "Repost" ads that were initially posted through kijiji website

### ISSUE THREAD

**Issue by jerry2key** [jackm/kijiji-manager#48]
Now sure if anyone has encountered the same issue, but I cannot repost ads when they were initially posted  via kijiji website, throws the following error:
**Cannot repost, ad file {c:/...}\kijiji-manager\instance\user\2464564564\16735445654645.xml does not exist.**

I guess we need to generate a .xml file based on the existing ads, somehow.

**Comment by jackm** [comment]
Yes this is a known limitation until a feature for importing ads and/or reposting ads created elsewhere is developed.

I have added a description of this and a workaround to the project readme in 12789a6.
