### ISSUE TITLE
Unable to repost payload or new ad - Unable to parse text: mismatched tag

### ISSUE THREAD

**Issue by thanksforkijijimanager** [jackm/kijiji-manager#54]
Unable to parse text: mismatched tag is the error message I am getting
Tried with existing ad, new ad and nothing will post

**Comment by greenappless** [comment]
Facing exactly the same issue for the past 2 days. Try refreshing a new IP address on the machine and then try manually posting _one_ listing.

**Comment by jackm** [comment]
This will likely require more debug information to find out what's happening. All I know right now is that the HTTP POST request to post the ad is likely returning a response that is not in the expected XML format.

I can also report that I myself do not have this issue and am still able to post and repost ads without issue.

**Comment by greenappless** [comment]
> This will likely require more debug information to find out what's happening. All I know right now is that the HTTP POST request to post the ad is likely returning a response that is not in the expected XML format.
> 
> I can also report that I myself do not have this issue and am still able to post and repost ads without issue.

I think the issue was in the instance >user> [**123423423**] folder. I have renamed it. Upon relisting a product, the new user number folder was created and now the ads relist without issues.

**Comment by greenappless** [comment]
> This will likely require more debug information to find out what's happening. All I know right now is that the HTTP POST request to post the ad is likely returning a response that is not in the expected XML format.
> 
> I can also report that I myself do not have this issue and am still able to post and repost ads without issue.

I think the issue was in the instance >user> [**123423423**] folder. I have renamed it. Upon relisting a product, the new user number folder was created and now the ads relist without issues.

**Comment by thanksforkijijimanager** [comment]
Everything seems to be working now

**Comment by jackm** [comment]
> > This will likely require more debug information to find out what's happening. All I know right now is that the HTTP POST request to post the ad is likely returning a response that is not in the expected XML format.
> > I can also report that I myself do not have this issue and am still able to post and repost ads without issue.
> 
> I think the issue was in the instance >user> [**123423423**] folder. I have renamed it. Upon relisting a product, the new user number folder was created and now the ads relist without issues.

kijiji-manager creates a user instance folder for the current logged in user using the unique kijiji user ID if it doesn't already exist. Then, when you repost an ad and kijiji-manager does not already have an ad payload xml file within the user instance folder it will create a new one using the existing ad details pulled from Kijiji. Deleting/moving the existing ad payload xml files would have had the same effect.

The difference I see here is that Kijiji rejected some data in the old ad payload xml file and gave back an error (which was incorrectly parsed).

**Comment by jackm** [comment]
[Release v0.2.3](../releases/tag/v0.2.3) contains a change which will write the problem response text to a local file to allow for further debugging. Since I don't run into this issue myself I may need help from others to find out what the error actually is.

**Comment by jackm** [comment]
Closing this as I do not have a reliable way to reproduce this due to lack of information.
