### ISSUE TITLE
Location data not being loaded properly

### ISSUE THREAD

**Issue by adm-gis** [jackm/kijiji-manager#56]
I think that the recent update to the Kijiji App came with a change to mapping/location services or at least the way the data are being read into the app.  When I post an ad through Kijiji-Manager, my location is now incorrect (it has been working great for over a year now).  I then tried posting through the regular Kijiji app on my browser and my location is correct.  

I've tried changing my postal code in Kijiji-Manager with no luck.  I've also tried adding more info to the open text location field in Kijiji-Manager, but that didn't work either.  

Any thoughts?

**Comment by jackm** [comment]
Location coordinates for an ad are derived from the postal code provided, and no other input field.
The [`pgeocode`](https://github.com/symerio/pgeocode) package is supposed to do this lookup so if there is a problem I would suspect it relating to that.

**Comment by jackm** [comment]
Personally I am able to still post new ads using my own postal code and it is able to get the correct location coordinates for it to appear on the ad itself.
