### ISSUE TITLE
New Ad post with image upload

### ISSUE THREAD

**Issue by Zediust** [jackm/kijiji-manager#59]
I seem to be getting an error when posting a new ad with image. The ad posting works when I post without an image.

I am getting the following error when posting an Ad with an image:

`Internal server error (Trace number: null )`

Upon some debugging, I found that it's the `r = self.session.post(api_endpoint, headers=headers, files=files)` on line 284 under `upload_image` function that's raising the error. @jackm Has the API for uploading images changed? if not, what's the issue here?

**Comment by Zediust** [comment]
The issue remains unresolved. @jackm, what's the best way to access API calls made by the Kijiji mobile app and view the corresponding data being sent? I'm willing to assist with further debugging and resolving this issue if someone can provide guidance.

**Comment by jackm** [comment]
I was able to post a new ad today and image uploads worked just fine.

If there was an exception caught, then there should be a `kijiji_manager_*.txt` file within your user instance directory (where you ad xml files are stored) containing more information.

**Comment by jackm** [comment]
Closing due to no response from user
