### ISSUE TITLE
Unable to log in after logging out of kijiji-manager

### ISSUE THREAD

**Issue by jsmoove9898** [jackm/kijiji-manager#63]
['api-error: Sorry, your username or password is incorrect. Please try again.']

On initial login, everything works as it should. However, when I logout and tried to login again, I get the above error. Is there a way to clear reset the token by any chance? 

I tried this one 3 different accounts and experienced the same problem on all 3. 

The account log on the mobile app and browser work but not through the kijiji-manager.

**Comment by jsmoove9898** [comment]
seems to be similar to issue #49. https://github.com/jackm/kijiji-manager/issues/49

but I want to check here first before I contact kijiji support.

**Comment by jackm** [comment]
I can confirm that I am able to logout and then login to kijiji-manager using my own account without any issues. I can also login to kijiji-manager from a clean browser (no cookies or cached data) using the same account.

Does not appear to be related to #49.

**Comment by jsmoove9898** [comment]
Any idea why this won't work on the manager but works through Kijiji app/browser? Also, if I were to raise a support ticket through kijiji, do you have any suggestions on how I can convey the message?

**Comment by jackm** [comment]
I am unsure as to why it seems to not work via kijiji-manager.

One other thing that I might suggest trying is to register a brand new Kijiji account and try to login via kijiji-manager using that to see if it works. If it does, the only thing I could conclude is that Kijiji has some sort of active block on your other accounts where it is detecting that you are not logging in using their official app or via the browser. It wouldn't really surprise me if they are employing detection methods like this as a way to either encourage users to purchase premium features or to combat spam.

**Comment by jsmoove9898** [comment]
thanks Jack. A new account worked. I'll just go with this for now. Closing issue.

**Comment by jerry2key** [comment]
@jsmoove9898 Facing the same issue, have you managed to solve it on your older accounts? Did you find the issue reoccurring on your new account?

**Comment by haal-laah** [comment]
Just encountered this issue and was able to sign in when using a VPN.
