### ISSUE TITLE
KijijiApiException: Unknown eBay API error

### ISSUE THREAD

**Issue by golemoak** [jackm/kijiji-manager#7]
Upon posting via web-app (Post >)

Multiple issues. 
My regular 10 (with or without +1) gives an invalid phone error and prevents posting.

I deleted phone and tried but got an error with image quality (which was ok)

I then tried a third time with a 1000x800 picture and got : 

`KijijiApiException: Unknown eBay API error`

**Comment by golemoak** [comment]
Seems to be image and/or checkboxes relevant. 
Tried with an original image and checkboxes ticked and it works

**Comment by jackm** [comment]
Could you provide steps to reproduce this?
Please include which ad category, ad specific drop-down menu selections, checkbox selections, and image filetype and dimensions.

**Comment by golemoak** [comment]
Try with a bad picture and all checkboxes unticked, but I think its the box that causes that specific issues.

**Comment by golemoak** [comment]
@jackm (Can you let me know how to properly trigger endpoints (e.g. http://localhost:5000/repost_all) via bash commands? I tried with wget but didn't trigger it properly.)

**Comment by jackm** [comment]
Most endpoints require that the user be logged in first. What this really means is that you must also send the "session" cookie along with any HTTP requests. My first step would be to try to include that cookie in your HTTP request.

**Comment by golemoak** [comment]
@jackm I'll try to find a chrome extension that visits URL (X) each (Y) TIME (or something similar). May not be optimal, but will surely do the job on a decent spec instance.

**Comment by jackm** [comment]
Can you comment on my previous question:

> Could you provide steps to reproduce this?
> Please include which ad category, ad specific drop-down menu selections, checkbox selections, and image filetype and dimensions.

**Comment by jackm** [comment]
[Version 0.1.1](../releases/tag/v0.1.1) allows uploading photos with dimensions less than 1000 px - you will not get an error anymore

**Comment by EdwardOak** [comment]
@jackm Thanks!

**Comment by jackm** [comment]
Issue with not allowing images with dimensions less than 1000px fixed in cc08516. Issue with phone numbers has been fixed in 0577df7.

Closing this.
